from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import shutil
import sys
import time
from pathlib import Path
from typing import Any

from .builder import (
    ORIGINAL_COMMAND_ANNOTATION,
    PROFILE_LABEL,
    SOURCE_ANNOTATION,
    UBUNTU_ARM64_IMAGE,
    BuildConfig,
    build_profile_job,
    inspect_job,
)
from .command import run, write_command_output
from .errors import InputError, ProfileJobBuilderError
from .validation import validate_source_job
from .yamlio import dump_yaml, load_yaml


def _add_source_options(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--input", "-i", required=True, help="Source Kubernetes Job YAML")
    parser.add_argument("--container", help="Target application container name")


def _add_build_options(parser: argparse.ArgumentParser) -> None:
    _add_source_options(parser)
    parser.add_argument("--output", "-o", help="Output YAML (stdout when omitted)")
    parser.add_argument("--name", help="Generated Profile Job name")
    parser.add_argument("--node", default="gx10-c206")
    parser.add_argument(
        "--nsys-host-path",
        default="/opt/nvidia/nsight-systems/2025.3.2",
    )
    parser.add_argument("--artifact-pvc", default="profile-artifacts")
    parser.add_argument("--collector-image", default=UBUNTU_ARM64_IMAGE)
    parser.add_argument("--init-image", default=UBUNTU_ARM64_IMAGE)
    parser.add_argument("--collector-timeout", type=int, default=3600)
    parser.add_argument("--no-collector", action="store_true")
    parser.add_argument(
        "--ephemeral-output",
        action="store_true",
        help="Use emptyDir instead of the artifact PVC (not persistent)",
    )
    parser.add_argument("--entrypoint", help="Full replacement executable")
    parser.add_argument("--arg", action="append", default=[], help="Replacement argument; repeat as needed")
    parser.add_argument(
        "--nsys-profile-arg",
        action="append",
        help=(
            "Replace the default nsys profile options; repeat once per option. "
            "Use --nsys-profile-arg=--option=value syntax."
        ),
    )
    parser.add_argument(
        "--application-capability",
        action="append",
        default=[],
        help="Linux capability added only to the profiled application container; repeat as needed",
    )


def _config(args: argparse.Namespace) -> BuildConfig:
    artifact_pvc = None if args.ephemeral_output else args.artifact_pvc
    return BuildConfig(
        target_container=args.container,
        node=args.node,
        name=args.name,
        nsys_host_path=args.nsys_host_path,
        artifact_pvc=artifact_pvc,
        collector_image=args.collector_image,
        init_image=args.init_image,
        collector_timeout_seconds=args.collector_timeout,
        include_collector=not args.no_collector,
        entrypoint=args.entrypoint,
        args=tuple(args.arg),
        nsys_profile_args=(
            tuple(args.nsys_profile_arg)
            if args.nsys_profile_arg
            else BuildConfig.nsys_profile_args
        ),
        application_capabilities=tuple(args.application_capability),
    )


def _write_yaml(document: dict[str, Any], output: str | None) -> None:
    rendered = dump_yaml(document)
    if output:
        Path(output).write_text(rendered, encoding="utf-8")
    else:
        sys.stdout.write(rendered)


def cmd_inspect(args: argparse.Namespace) -> int:
    source = load_yaml(args.input)
    print(json.dumps(inspect_job(source, args.container), ensure_ascii=False, indent=2))
    return 0


def cmd_validate(args: argparse.Namespace) -> int:
    source = load_yaml(args.input)
    validate_source_job(source, args.container, args.entrypoint, args.arg)
    print("valid")
    return 0


def cmd_build(args: argparse.Namespace) -> int:
    source = load_yaml(args.input)
    result = build_profile_job(source, _config(args))
    _write_yaml(result, args.output)
    return 0


def cmd_diff(args: argparse.Namespace) -> int:
    source = load_yaml(args.input)
    result = build_profile_job(source, _config(args))
    before = dump_yaml(source).splitlines(keepends=True)
    after = dump_yaml(result).splitlines(keepends=True)
    sys.stdout.writelines(
        difflib.unified_diff(
            before,
            after,
            fromfile=args.input,
            tofile=args.output or "profile-job.yaml",
        )
    )
    return 0


def _assert_profile_job(document: dict[str, Any]) -> None:
    labels = document.get("metadata", {}).get("labels", {})
    if labels.get(PROFILE_LABEL) != "true":
        raise InputError("run accepts only YAML generated by Profile Job Builder")


def cmd_run(args: argparse.Namespace) -> int:
    document = load_yaml(args.input)
    _assert_profile_job(document)
    command = ["kubectl"]
    if args.kubeconfig:
        command.extend(["--kubeconfig", args.kubeconfig])
    if args.context:
        command.extend(["--context", args.context])
    if args.namespace:
        command.extend(["--namespace", args.namespace])
    if not args.skip_server_dry_run:
        run([*command, "create", "--dry-run=server", "-f", args.input])
    run([*command, "create", "-f", args.input])
    print(f"created job/{document['metadata']['name']}")
    return 0


def _kubectl_base(args: argparse.Namespace) -> list[str]:
    command = ["kubectl"]
    if args.kubeconfig:
        command.extend(["--kubeconfig", args.kubeconfig])
    if args.context:
        command.extend(["--context", args.context])
    command.extend(["--namespace", args.namespace])
    return command


def cmd_collect(args: argparse.Namespace) -> int:
    destination = Path(args.destination).resolve()
    if destination.exists():
        if not destination.is_dir() or any(destination.iterdir()):
            raise InputError(f"destination must be new or empty: {destination}")
    destination.mkdir(parents=True, exist_ok=True)

    kubectl = _kubectl_base(args)
    source_pod = _wait_for_source_pod(kubectl, args.job, args.timeout)
    _wait_for_container_running(
        kubectl, source_pod, "profile-collector", args.timeout
    )

    output_dir = f"/profile-output/{args.job}"
    wait_script = (
        f"deadline=$(( $(date +%s) + {args.timeout} )); "
        f"while [ ! -f {output_dir}/.collector-ready ]; do "
        'if [ "$(date +%s)" -ge "$deadline" ]; then exit 124; fi; '
        "sleep 2; done"
    )
    run(
        [
            *kubectl,
            "exec",
            source_pod,
            "-c",
            "profile-collector",
            "--",
            "/bin/sh",
            "-ceu",
            wait_script,
        ]
    )
    run(
        [
            *kubectl,
            "cp",
            f"{source_pod}:{output_dir}/.",
            str(destination),
            "-c",
            "profile-collector",
        ]
    )

    write_command_output(
        [*kubectl, "logs", source_pod, "-c", args.container],
        destination / "application.log",
    )
    shutil.copyfile(
        Path(args.profile_job_yaml).resolve(),
        destination / "profile-job.yaml",
    )
    run(
        [
            *kubectl,
            "exec",
            source_pod,
            "-c",
            "profile-collector",
            "--",
            "touch",
            f"{output_dir}/.collected",
        ]
    )
    pod_json = _wait_for_collector_exit(kubectl, source_pod, args.timeout)
    (destination / "pod.json").write_text(pod_json, encoding="utf-8")
    metadata = _write_collected_metadata(
        destination=destination,
        job_name=args.job,
        namespace=args.namespace,
        target_container=args.container,
    )
    print(destination)
    if metadata.get("overallStatus") != "success":
        reason = metadata.get("failureReason") or "unknown_failure"
        raise InputError(
            f"collection failed: {reason}; diagnostic artifacts saved at {destination}"
        )
    return 0


def _wait_for_source_pod(
    kubectl: list[str], job_name: str, timeout: int
) -> str:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        pod_result = run(
            [
                *kubectl,
                "get",
                "pods",
                "-l",
                f"job-name={job_name}",
                "-o",
                "jsonpath={.items[0].metadata.name}",
            ],
            capture=True,
        )
        pod_name = pod_result.stdout.strip()
        if pod_name:
            return pod_name
        time.sleep(2)
    raise InputError(f"no Pod found for job {job_name!r} within {timeout}s")


def _wait_for_collector_exit(
    kubectl: list[str], pod_name: str, timeout: int
) -> str:
    deadline = time.monotonic() + timeout
    last_document = ""
    while time.monotonic() < deadline:
        result = run(
            [*kubectl, "get", f"pod/{pod_name}", "-o", "json"],
            capture=True,
        )
        last_document = result.stdout
        pod = json.loads(last_document)
        if _container_status(pod, "profile-collector"):
            return last_document
        time.sleep(2)
    raise InputError(
        f"profile-collector did not terminate within {timeout}s after collection"
    )


def _wait_for_container_running(
    kubectl: list[str],
    pod_name: str,
    container_name: str,
    timeout: int,
) -> None:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        result = run(
            [*kubectl, "get", f"pod/{pod_name}", "-o", "json"],
            capture=True,
        )
        pod = json.loads(result.stdout)
        statuses = pod.get("status", {}).get("containerStatuses", [])
        status = next(
            (
                item
                for item in statuses
                if isinstance(item, dict) and item.get("name") == container_name
            ),
            {},
        )
        state = status.get("state", {}) if isinstance(status, dict) else {}
        if isinstance(state.get("running"), dict):
            return
        terminated = state.get("terminated")
        if isinstance(terminated, dict):
            raise InputError(
                f"container {container_name!r} terminated before collection "
                f"(exitCode={terminated.get('exitCode')})"
            )
        time.sleep(2)
    raise InputError(
        f"container {container_name!r} did not start within {timeout}s"
    )


def _container_status(pod: dict[str, Any], container_name: str) -> dict[str, Any]:
    statuses = pod.get("status", {}).get("containerStatuses", [])
    for status in statuses:
        if isinstance(status, dict) and status.get("name") == container_name:
            terminated = status.get("state", {}).get("terminated")
            return terminated if isinstance(terminated, dict) else {}
    return {}


def _write_collected_metadata(
    *,
    destination: Path,
    job_name: str,
    namespace: str,
    target_container: str,
) -> dict[str, Any]:
    pod = json.loads((destination / "pod.json").read_text(encoding="utf-8"))
    job = load_yaml(str(destination / "profile-job.yaml"))
    existing_path = destination / "profile-metadata.json"
    existing: dict[str, Any] = {}
    if existing_path.exists():
        try:
            loaded = json.loads(existing_path.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                existing = loaded
        except (OSError, json.JSONDecodeError):
            existing = {}

    containers = pod.get("spec", {}).get("containers", [])
    target = next(
        (
            item
            for item in containers
            if isinstance(item, dict) and item.get("name") == target_container
        ),
        {},
    )
    annotations = job.get("metadata", {}).get("annotations", {})
    limits = target.get("resources", {}).get("limits", {})
    gpu_resource = next(
        (
            resource
            for resource in ("nvidia.com/gpu.shared", "nvidia.com/gpu")
            if resource in limits
        ),
        None,
    )
    original_command: list[str] = []
    try:
        parsed_command = json.loads(annotations.get(ORIGINAL_COMMAND_ANNOTATION, "[]"))
        if isinstance(parsed_command, list) and all(
            isinstance(item, str) for item in parsed_command
        ):
            original_command = parsed_command
    except json.JSONDecodeError:
        pass

    report = destination / "profile.nsys-rep"
    report_size = report.stat().st_size if report.exists() else None
    report_sha256 = None
    if report.exists():
        digest = hashlib.sha256()
        with report.open("rb") as stream:
            for chunk in iter(lambda: stream.read(1024 * 1024), b""):
                digest.update(chunk)
        report_sha256 = digest.hexdigest()

    expected_checksum = existing.get("expected_checksum")
    collector_checksum = existing.get("actual_checksum")
    checksum_match = (
        bool(expected_checksum)
        and bool(report_sha256)
        and expected_checksum == report_sha256
    )
    overall_status = existing.get("overall_status") or existing.get("status")
    failure_reason = existing.get("failure_reason")
    if expected_checksum and report_sha256 and not checksum_match:
        overall_status = "failed"
        failure_reason = "local_checksum_mismatch"

    app_status = _container_status(pod, target_container)
    collector_status = _container_status(pod, "profile-collector")
    metadata = {
        "schemaVersion": "v1",
        "sourceJob": annotations.get(SOURCE_ANNOTATION),
        "profileJob": job_name,
        "namespace": namespace,
        "pod": pod.get("metadata", {}).get("name"),
        "node": pod.get("spec", {}).get("nodeName"),
        "targetContainer": target_container,
        "targetImage": target.get("image"),
        "gpuResource": gpu_resource,
        "gpuMode": (
            "shared"
            if gpu_resource == "nvidia.com/gpu.shared"
            else "dedicated" if gpu_resource == "nvidia.com/gpu" else None
        ),
        "workloadCommand": original_command,
        "startedAt": pod.get("status", {}).get("startTime"),
        "finishedAt": job.get("status", {}).get("completionTime")
        or existing.get("finished_at"),
        "applicationProfilerExitCode": app_status.get("exitCode"),
        "applicationProfilerReason": app_status.get("reason"),
        "collectorExitCode": collector_status.get("exitCode"),
        "collectorReason": collector_status.get("reason"),
        "nsysVersion": existing.get("nsys_version"),
        "overallStatus": overall_status,
        "failureReason": failure_reason,
        "reportExists": existing.get("report_exists", report.exists()),
        "reportValid": existing.get("report_valid"),
        "statsComplete": existing.get("stats_complete"),
        "expectedReportSha256": expected_checksum,
        "collectorReportSha256": collector_checksum,
        "localChecksumMatch": checksum_match,
        "reportSize": report_size,
        "reportSha256": report_sha256,
    }
    existing_path.write_text(
        json.dumps(metadata, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return metadata


def cmd_clean(args: argparse.Namespace) -> int:
    command = _kubectl_base(args)
    run([*command, "delete", f"job/{args.job}", "--ignore-not-found=true"])
    print(f"deleted job/{args.job}; persistent artifacts were not removed")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="profile-job-builder")
    subparsers = parser.add_subparsers(dest="subcommand", required=True)

    inspect_parser = subparsers.add_parser("inspect")
    _add_source_options(inspect_parser)
    inspect_parser.set_defaults(func=cmd_inspect)

    validate_parser = subparsers.add_parser("validate")
    _add_source_options(validate_parser)
    validate_parser.add_argument("--entrypoint")
    validate_parser.add_argument("--arg", action="append", default=[])
    validate_parser.set_defaults(func=cmd_validate)

    build_parser_command = subparsers.add_parser("build")
    _add_build_options(build_parser_command)
    build_parser_command.set_defaults(func=cmd_build)

    diff_parser = subparsers.add_parser("diff")
    _add_build_options(diff_parser)
    diff_parser.set_defaults(func=cmd_diff)

    run_parser = subparsers.add_parser("run")
    run_parser.add_argument("--input", "-i", required=True)
    run_parser.add_argument("--kubeconfig")
    run_parser.add_argument("--context")
    run_parser.add_argument("--namespace")
    run_parser.add_argument("--skip-server-dry-run", action="store_true")
    run_parser.set_defaults(func=cmd_run)

    collect_parser = subparsers.add_parser("collect")
    collect_parser.add_argument("--job", required=True)
    collect_parser.add_argument("--container", required=True)
    collect_parser.add_argument("--destination", "-o", required=True)
    collect_parser.add_argument(
        "--profile-job-yaml",
        required=True,
        help="Locally reviewed Profile Job YAML (avoids requiring get jobs RBAC)",
    )
    collect_parser.add_argument("--namespace", default="profiling")
    collect_parser.add_argument("--kubeconfig")
    collect_parser.add_argument("--context")
    collect_parser.add_argument("--timeout", type=int, default=3600)
    collect_parser.set_defaults(func=cmd_collect)

    clean_parser = subparsers.add_parser("clean")
    clean_parser.add_argument("--job", required=True)
    clean_parser.add_argument("--namespace", default="profiling")
    clean_parser.add_argument("--kubeconfig")
    clean_parser.add_argument("--context")
    clean_parser.set_defaults(func=cmd_clean)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.func(args))
    except ProfileJobBuilderError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
